config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  root :to => "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :presence => true
  validates :body, :presence => true

  belongs_to :user

  def self.whitelisted_attributes
    [:title, :body, :body, :user_id]
  end
end
  

app/models/user.rb
class User < ApplicationRecord
  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true

  has_many :blogs 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :load_user

  def index
    @blogs = @user.blogs   
  end

  def show 
    @blog = @user.blogs.find(params[:id])
  end

  def new
    @blog = @user.blogs.new 
  end

  def create
    @blog = Blog.new(params[:blog].permit(Blog.whitelisted_attributes))

    if !@blog.save
      @user = User.find(@blog.user_id)
      render :new
    else
      redirect_to blog_path(@blog, :user_id => @blog.user_id)
    end
  end

  def load_user
    if !params[:user_id].nil?
      @user = User.find(params[:user_id]) 
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.order(:email).all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <%= f.hidden_field :user_id, :value => @user.id %>
    <%= f.submit %>
<% end %>

app/views/blogs/index.html.erb
<h1><%="#{@user.name}'s Blog Posts!"%><h1> 

<ul>

<% @blogs.each do |blog| %>
<li><%= link_to blog.title, blog_path(blog, :user_id => @user.id) %></li>
<% end %>

</ul>

<%= link_to "Create New Blog", new_blog_path(:user_id => @user.id) %>

app/views/blogs/new.html.erb
<h1>Create a New Blog!</h1>
<%= render :partial => "form" %>

app/views/blogs/show.html.erb
<h1> <%= @blog.title %> </h1>

<p> <%= @blog.body %> </p>

app/views/home/index.erb
<h1>Renee!</h1>

<ul>
<%  @users.each do |user| %> 
  <li><%= link_to(user.name, blogs_path(:user_id => user.id)).html_safe %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Renee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>